# Generated by Django 4.2.9 on 2024-02-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image_as_file",
            field=models.FileField(null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
