# Generated by Django 4.2.9 on 2024-03-26 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_userprofile_image_as_file_alter_userprofile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="image_as_file",
        ),
    ]
