# Generated by Django 4.2.9 on 2024-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_outlet", "0003_book_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug2",
            field=models.SlugField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
