# Generated by Django 4.2.9 on 2024-01-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_outlet", "0009_country_alter_address_street_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_countries",
            field=models.ManyToManyField(
                related_name="books", to="book_outlet.country"
            ),
        ),
    ]
