# Generated by Django 4.2.9 on 2024-01-25 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book_outlet", "0010_alter_book_published_countries"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
    ]
